### ISSUE TITLE
Having and issue with the buttons and underlining in my code

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/modularity-mindfulness#1]
there are a number of small details wrong with my code but the buttons underlining at the beginning links and the symbolisms image padding is effecting me the most 

@charlie-quinn

**Comment by charlie-quinn** [comment]
Hey @JiffyBees can you push the latest commit you've made so I can see what your buttons are doing please? Currently, I'm only able to view your last commit from 2 days ago.

**Comment by JiffyBees** [comment]
Ok it has been pushed, sorry about that.
@charlie-quinn

**Comment by JiffyBees** [comment]
Oh sorry it try pushing it

**Comment by charlie-quinn** [comment]
@JiffyBees 
- [x] remove the `btn` class on your navigation's `<li>` tags (these wouldn't be classified as buttons, just regular 'ol links)
- [x] your `<ul>` should be using the `.list-group-inline` class instead of the `island-1-4 mega` classes (better semantics, and an easier rule to follow in the long-run)
- [x] now add your `border-bottom: solid 2px #8bc9d9` & how you'd like them to look on hover 🎨

**Comment by JiffyBees** [comment]
alright that worked thank you. 

if its not to much trouble can you also help me with the symbol button on the medium screen size it seems to get cut in half due to my grid. 

I also can't find the coding cheat sheets to unify the text so it scales evenly together.
@charlie-quinn

**Comment by charlie-quinn** [comment]
@JiffyBees 
- [ ] Make sure your buttons also include the `btn` class.
- [ ] We want to try and reuse as much of our code as possible so that we aren't retargeting and rewriting lines. We can do this by removing your `border` class + additional `btn` styling in your `main.css` file, and adding:
  - `border-width: .1em;`to your `btn-ghost` class in your `main.css` file
- [ ] Wrap your buttons inside of a `<div>` and add the `push` class to give them a nice margin-bottom below.

**Comment by JiffyBees** [comment]
@charlie-quinn
alright I made those changes

**Comment by charlie-quinn** [comment]
@JiffyBees wonderful!

Don't forget to close this issue once it's been resolved. ✅

**Comment by JiffyBees** [comment]
mark-bot isn't accepting the html but I will close this issue soon.
thanks
@charlie-quinn
